// Source: https://wiki.openraildata.com/index.php/TOC_Codes
export const TOC_NAMES: Record<string, string> = {
  "synthetic:operator:demo": "Demonstration service",
  "AW": "Transport for Wales",
  "CC": "c2c",
  "CH": "Chiltern Railways",
  "CS": "Caledonian Sleeper",
  "EM": "East Midlands Railway",
  "ES": "Eurostar",
  "GC": "Grand Central",
  "GN": "Great Northern",
  "GR": "LNER",
  "GW": "Great Western Railway",
  "GX": "Gatwick Express",
  "HT": "Hull Trains",
  "HX": "Heathrow Express",
  "IL": "Island Line",
  "LE": "Greater Anglia",
  "LM": "West Midlands Trains",
  "LO": "London Overground",
  "LT": "Elizabeth Line",
  "ME": "Merseyrail",
  "NT": "Northern",
  "NY": "North Yorkshire Moors",
  "SE": "Southeastern",
  "SN": "Southern",
  "SR": "ScotRail",
  "SW": "South Western Railway",
  "TL": "Thameslink",
  "TP": "TransPennine Express",
  "TW": "Tyne & Wear Metro",
  "VT": "Avanti West Coast",
  "XC": "CrossCountry",
  "XR": "Elizabeth Line",
  "DB": "DB Cargo",
  "DC": "Devon & Cornwall Railways",
  "DR": "Direct Rail Services",
  "FL": "Freightliner",
  "GB": "GB Railfreight",
  "LR": "Locomotive Services",
  "RF": "Rail Operations Group",
  "WR": "West Coast Railways",
  "LN": "Network Rail",
  "NR": "Network Rail",
  "ZZ": "Unidentified",
  "XX": "Unknown",
};

export function getTocName(tocId: string): string {
  return TOC_NAMES[tocId] || tocId;
}
